# Generated by Django 2.1.7 on 2019-03-14 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issue_protocol', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='credential_batch',
            old_name='username',
            new_name='user_name',
        ),
    ]
