# Generated by Django 2.1.7 on 2019-03-14 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue_protocol', '0003_auto_20190314_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='credential_batch',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='credential_batch',
            name='user_name',
            field=models.CharField(max_length=120),
        ),
    ]
