# Generated by Django 2.1.7 on 2019-03-14 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue_protocol', '0004_auto_20190314_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='credential_batch',
            name='batchId',
            field=models.CharField(default=1, max_length=500, unique=True),
            preserve_default=False,
        ),
    ]
