# Generated by Django 2.1.7 on 2019-03-15 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue_protocol', '0005_credential_batch_batchid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credential_batch',
            name='batchId',
            field=models.CharField(max_length=500),
        ),
    ]
