# Generated by Django 2.1.7 on 2019-03-15 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue_protocol', '0006_auto_20190315_1449'),
    ]

    operations = [
        migrations.CreateModel(
            name='Key',
            fields=[
                ('keyId', models.AutoField(primary_key=True, serialize=False)),
                ('publicKey', models.TextField()),
                ('secretKey', models.TextField()),
            ],
        ),
    ]
