# Generated by Django 2.1.7 on 2019-03-03 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Credential',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_cred', models.CharField(max_length=100)),
                ('date_of_creation', models.DateTimeField(verbose_name='date created')),
            ],
        ),
    ]
