# Generated by Django 2.1.7 on 2019-03-03 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='credential',
            name='id_cred',
        ),
    ]
