# Generated by Django 2.1.7 on 2019-03-03 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_remove_credential_id_cred'),
    ]

    operations = [
        migrations.RenameField(
            model_name='credential',
            old_name='date_of_creation',
            new_name='date',
        ),
    ]
