# Generated by Django 2.1.7 on 2019-03-03 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_auto_20190303_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='credential',
            name='issuer',
            field=models.CharField(default='No issuer', max_length=200),
        ),
    ]
