# Generated by Django 2.1.7 on 2019-03-15 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PublicPrivateKeys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_keys', models.TextField(blank=True)),
                ('private_keys', models.TextField(blank=True)),
                ('groups', models.TextField(blank=True)),
                ('policy', models.CharField(max_length=500, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField()),
                ('user', models.TextField()),
            ],
        ),
    ]
