# Generated by Django 2.1.7 on 2019-03-15 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_protocols', '0002_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='newToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField()),
                ('user', models.TextField()),
            ],
        ),
    ]
